### ISSUE TITLE
Remove print about API

### ISSUE THREAD

**Issue by Tmarinus** [nlfmt/pyqt-colorpicker#11]
I like this simple easy way to pick a color, great widget thank you. 

But in the __init__ file there is a print statement that if imported is always printed. Could be nice if this was removed.

```
print("Using QtPy API: %s" % API_NAME)
```

**Comment by Tmarinus** [comment]
#12 Created pull request

**Comment by tomfln** [comment]
Good catch, that seems to be a leftover debug statement..
If you can implement the changes i proposed in the PR, we can merge it asap!
