### ISSUE TITLE
Alpha channel

### ISSUE THREAD

**Issue by MarselJIT** [nlfmt/pyqt-colorpicker#2]
Hello! This is very pretty qcolor widget. Thank. Can you add alpha channel changer spinbox for this widget?

**Comment by tomfln** [comment]
I'm glad you like it. Yes i will add alpha selection ASAP, I'm currently working on it.

**Comment by tomfln** [comment]
Alpha selection is now possible. Check out the newest release's README to learn more.

**Comment by MarselJIT** [comment]
> Alpha selection is now possible. Check out the newest release's README to learn more.

thank you again for your work.

**Comment by MarselJIT** [comment]
my implementation
![pcit](https://user-images.githubusercontent.com/61140544/97894246-1adbc180-1d54-11eb-880b-75316c4db633.JPG)
