### ISSUE TITLE
Cannot simple click to select color tone

### ISSUE THREAD

**Issue by BootsManOut** [nlfmt/pyqt-colorpicker#6]
Hi there!
Thank you for this neat widget!

When you click the color bar, nothing happens, which is very counter-intuitive.
You have to click and drag for the slider to respond.

Could this be implemented, that you can simply click the color bar and the slider jumps to clicked location?

![Color Picker UX](https://github.com/nlfmt/pyqt-colorpicker/assets/63544082/d8b41034-914b-409c-8323-80a870b245ef)

**Comment by tomfln** [comment]
You're right, it seems i forgot to hook up the mouse press event as well. Should be an easy fix
